export const FETCH_BUDGETS = 'BUDGETS/FETCH_BUDGETS'
export const REQUEST_BUDGETS = 'BUDGETS/REQUEST_BUDGETS'
export const ADD_BUDGET = 'BUDGETS/ADD_BUDGET'
export const DELETE_BUDGET = 'BUDGETS/DELETE_BUDGET'
export const EDIT_BUDGET = 'BUDGETS/EDIT_BUDGET'

export const FETCH_EXPENSES = 'EXPENSES/FETCH_EXPENSES'
export const ADD_EXPENSE = 'EXPENSES/ADD_EXPENSE'
export const DELETE_EXPENSE = 'EXPENSES/DELETE_EXPENSE'

export const REQUEST_EXPENSES = 'EXPENSES/REQUEST_EXPENSES'

export const SHOW_LOADER = 'APP/SHOW_LOADER'
export const HIDE_LOADER = 'APP/HIDE_LOADER'
export const SHOW_ALERT = 'APP/SHOW_ALERT'
export const HIDE_ALERT = 'APP/HIDE_ALERT'
